//  Tool to merge unigram counts of 2 languages generated by vocab_count
//
//  Copyright (c) 2014 The Board of Trustees of
//  The Leland Stanford Junior University. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//
//
//  For more information, bug reports, fixes, contact:
//    Jilei Wang (wangjileiRUC@gmail.com)

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define MAX_STRING_LENGTH 1000

int verbose = 2; // 0, 1, or 2
char *filename1, *filename2;

/* Efficient string comparison */
int scmp( char *s1, char *s2 ) {
    while (*s1 != '\0' && *s1 == *s2) {s1++; s2++;}
    return(*s1 - *s2);
}

/* Vocab frequency comparison; break ties alphabetically */
int CompareVocabTie(long long count1, long long count2, char *word1, char *word2) {
    long long c;
    if ( (c = count2 - count1) != 0) return ( c > 0 ? 1 : -1 );
    else return (scmp(word1, word2));
    
}

int merge_files() {
    char format[20], word1_prefix[MAX_STRING_LENGTH + 2], word2_prefix[MAX_STRING_LENGTH + 2];
    char *word1, * word2;
    FILE *fid1, *fid2;
    int ret1, ret2;
    long long count1, count2;

    word1 = word1_prefix + 1;
    word2 = word2_prefix + 1;
    word1_prefix[0] = '1';
    word2_prefix[0] = '2';

    fid1 = fopen(filename1,"r");
    if (fid1 == NULL) {fprintf(stderr,"Unable to open vocab file 1: %s.\n",filename1); return 1;}
    fid2 = fopen(filename2,"r");
    if (fid2 == NULL) {fprintf(stderr,"Unable to open vocab file 2: %s.\n",filename2); return 1;}

    sprintf(format,"%%%ds %%lld", MAX_STRING_LENGTH);
    ret1 = fscanf(fid1, format, word1, &count1);
    ret2 = fscanf(fid2, format, word2, &count2);
    while (ret1 != EOF && ret2 != EOF) {
        if (CompareVocabTie(count1, count2, word1, word2) <= 0) {
            printf("%s %lld\n", word1_prefix, count1);
            ret1 = fscanf(fid1, format, word1, &count1);
        }
        else {
            printf("%s %lld\n", word2_prefix, count2);
            ret2 = fscanf(fid2, format, word2, &count2);
        }
    }
    while (ret1 != EOF) {
        printf("%s %lld\n", word1_prefix, count1);
        ret1 = fscanf(fid1, format, word1, &count1);
    }
    while (ret1 != EOF) {
        printf("%s %lld\n", word2_prefix, count2);
        ret2 = fscanf(fid2, format, word2, &count2);
    }
    return 0;
}

int find_arg(char *str, int argc, char **argv) {
    int i;
    for (i = 1; i < argc; i++) {
        if (!scmp(str, argv[i])) {
            if (i == argc - 1) {
                printf("No argument given for %s\n", str);
                exit(1);
            }
            return i;
        }
    }
    return -1;
}

int main(int argc, char **argv) {
    int i;
    filename1 = malloc(sizeof(char) * MAX_STRING_LENGTH);
    filename2 = malloc(sizeof(char) * MAX_STRING_LENGTH);

    if (argc == 1) {
        printf("Merge 2 unigram count files of 2 languages\n");
        printf("Author: Jilei Wang (wangjileiRUC@gmail.com)\n\n");
        printf("Usage options:\n");
        printf("\t-verbose <int>\n");
        printf("\t\tSet verbosity: 0, 1, or 2 (default)\n");
        printf("\t-file1 <int>\n");
        printf("\t\tThe first vocab count file\n");
        printf("\t-file2 <int>\n");
        printf("\t\tThe second vocab count file\n");
        printf("\nExample usage:\n");
        printf("./bi_vocab_count -verbose 2 -file1 vocab.zh.txt -file2 vocab.ja.txt > vocab.bi.txt\n");
        return 0;
    }
    
    if ((i = find_arg((char *)"-verbose", argc, argv)) > 0) verbose = atoi(argv[i + 1]);
    if ((i = find_arg((char *)"-file1", argc, argv)) > 0) strcpy(filename1, argv[i + 1]);
    if ((i = find_arg((char *)"-file2", argc, argv)) > 0) strcpy(filename2, argv[i + 1]);
    return merge_files();
}

